import { PrismaClient, Goal, PeptideCategory } from "@prisma/client";

const prisma = new PrismaClient();

type PeptideSeed = {
  name: string;
  slug: string;
  category: PeptideCategory;
  goals: Goal[];
  description: string;
  typicalDoseMin: number;
  typicalDoseMax: number;
  doseUnit: string;
  frequency: string;
  cycleWeeksMin: number;
  cycleWeeksMax: number;
  cautions: string;
  priceOneTimeCents: number;
  isRx: boolean;
  halfLifeHours: number | null;
  researchStatus: string;
};

const peptides: PeptideSeed[] = [
  {
    name: "BPC-157",
    slug: "bpc-157",
    category: "HEALING_RECOVERY",
    goals: ["RECOVERY", "INJURY_REPAIR", "GENERAL_WELLNESS"],
    description:
      "Synthetic peptide most commonly discussed in soft-tissue and gut-lining recovery research.",
    typicalDoseMin: 200,
    typicalDoseMax: 500,
    doseUnit: "mcg",
    frequency: "once or twice daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 8,
    cautions: "Limited human trial data. Avoid if pregnant or with a history of cancer; consult a physician.",
    priceOneTimeCents: 6499,
    isRx: false,
    halfLifeHours: 5,
    researchStatus: "Widely researched",
  },
  {
    name: "TB-500",
    slug: "tb-500",
    category: "HEALING_RECOVERY",
    goals: ["RECOVERY", "INJURY_REPAIR"],
    description:
      "Synthetic fragment of thymosin beta-4, frequently stacked with BPC-157 in recovery protocols.",
    typicalDoseMin: 2,
    typicalDoseMax: 5,
    doseUnit: "mg",
    frequency: "twice weekly",
    cycleWeeksMin: 4,
    cycleWeeksMax: 6,
    cautions: "Often stacked with BPC-157. Not studied long-term in humans; avoid with active malignancy.",
    priceOneTimeCents: 7999,
    isRx: false,
    halfLifeHours: 60,
    researchStatus: "Widely researched",
  },
  {
    name: "GHK-Cu",
    slug: "ghk-cu",
    category: "COSMETIC",
    goals: ["SKIN_HAIR", "LONGEVITY", "RECOVERY"],
    description:
      "Copper peptide discussed in skin remodeling and topical recovery contexts.",
    typicalDoseMin: 1,
    typicalDoseMax: 3,
    doseUnit: "mg",
    frequency: "once daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 12,
    cautions: "Topical forms are widely available and gentle; injectable forms should be sourced and dosed carefully.",
    priceOneTimeCents: 5499,
    isRx: false,
    halfLifeHours: 2,
    researchStatus: "Widely researched",
  },
  {
    name: "CJC-1295/Ipamorelin",
    slug: "cjc-1295-ipamorelin",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN", "RECOVERY", "SLEEP", "LONGEVITY"],
    description:
      "Combination GHRH analog + ghrelin mimetic, commonly discussed in body-composition and recovery contexts.",
    typicalDoseMin: 100,
    typicalDoseMax: 300,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 8,
    cycleWeeksMax: 16,
    cautions: "Inject before bed on empty stomach for best effect. May cause water retention or mild flushing initially.",
    priceOneTimeCents: 8999,
    isRx: false,
    halfLifeHours: 100,
    researchStatus: "Widely researched",
  },
  {
    name: "Ipamorelin",
    slug: "ipamorelin",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN", "RECOVERY", "SLEEP"],
    description:
      "Selective ghrelin receptor agonist, often discussed for its targeted GH-pulse profile.",
    typicalDoseMin: 100,
    typicalDoseMax: 300,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 8,
    cycleWeeksMax: 16,
    cautions: "Generally well tolerated; often paired with a GHRH analog.",
    priceOneTimeCents: 5999,
    isRx: false,
    halfLifeHours: 2,
    researchStatus: "Widely researched",
  },
  {
    name: "Sermorelin",
    slug: "sermorelin",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN", "RECOVERY", "SLEEP", "LONGEVITY"],
    description:
      "GHRH analog historically used in pediatric GH-deficiency research; now broadly discussed in longevity contexts.",
    typicalDoseMin: 200,
    typicalDoseMax: 500,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 8,
    cycleWeeksMax: 24,
    cautions: "Generally well tolerated. Avoid in active malignancy; effects build gradually over weeks.",
    priceOneTimeCents: 7499,
    isRx: false,
    halfLifeHours: 0.25,
    researchStatus: "Widely researched",
  },
  {
    name: "Tesamorelin",
    slug: "tesamorelin",
    category: "GROWTH_HORMONE",
    goals: ["FAT_LOSS", "MUSCLE_GAIN"],
    description:
      "FDA-approved GHRH analog for HIV-associated lipodystrophy; off-label use requires a prescriber.",
    typicalDoseMin: 1,
    typicalDoseMax: 2,
    doseUnit: "mg",
    frequency: "once daily",
    cycleWeeksMin: 12,
    cycleWeeksMax: 26,
    cautions: "Prescription-only. Requires provider evaluation before use.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 0.5,
    researchStatus: "FDA-approved (Egrifta) for a specific indication",
  },
  {
    name: "Hexarelin",
    slug: "hexarelin",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN", "RECOVERY"],
    description:
      "Potent ghrelin mimetic studied for GH release; among the more potent secretagogues discussed in literature.",
    typicalDoseMin: 100,
    typicalDoseMax: 200,
    doseUnit: "mcg",
    frequency: "once or twice daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 8,
    cautions: "May cause desensitization with prolonged continuous use; cycle carefully.",
    priceOneTimeCents: 6999,
    isRx: false,
    halfLifeHours: 1.2,
    researchStatus: "Research-stage",
  },
  {
    name: "AOD-9604",
    slug: "aod-9604",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS"],
    description:
      "Modified HGH fragment studied specifically for fat-metabolism pathways without broader GH effects.",
    typicalDoseMin: 250,
    typicalDoseMax: 500,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 8,
    cycleWeeksMax: 12,
    cautions: "Limited long-term human data.",
    priceOneTimeCents: 7299,
    isRx: false,
    halfLifeHours: 2,
    researchStatus: "Research-stage",
  },
  {
    name: "Melanotan II",
    slug: "melanotan-ii",
    category: "COSMETIC",
    goals: ["SKIN_HAIR", "LIBIDO"],
    description:
      "Melanocortin agonist discussed in pigmentation and libido research contexts.",
    typicalDoseMin: 0.25,
    typicalDoseMax: 1,
    doseUnit: "mg",
    frequency: "once daily",
    cycleWeeksMin: 2,
    cycleWeeksMax: 4,
    cautions: "Can cause nausea, flushing, and darkening of existing moles/freckles. Not recommended for those with a history of melanoma.",
    priceOneTimeCents: 5999,
    isRx: false,
    halfLifeHours: 4,
    researchStatus: "Research-stage",
  },
  {
    name: "PT-141 (Bremelanotide)",
    slug: "pt-141",
    category: "SEXUAL_HEALTH",
    goals: ["LIBIDO"],
    description:
      "FDA-approved for HSDD in premenopausal women under prescription; melanocortin pathway agonist.",
    typicalDoseMin: 1,
    typicalDoseMax: 2,
    doseUnit: "mg",
    frequency: "as needed, max 1x/24h",
    cycleWeeksMin: 1,
    cycleWeeksMax: 12,
    cautions: "Prescription-only. Can cause nausea, flushing, and transient blood pressure increases.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 2.7,
    researchStatus: "FDA-approved (Vyleesi) for a specific indication",
  },
  {
    name: "Semaglutide",
    slug: "semaglutide",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS", "GENERAL_WELLNESS"],
    description:
      "GLP-1 receptor agonist approved for type 2 diabetes and chronic weight management.",
    typicalDoseMin: 0.25,
    typicalDoseMax: 2.4,
    doseUnit: "mg",
    frequency: "once weekly",
    cycleWeeksMin: 12,
    cycleWeeksMax: 52,
    cautions: "Prescription-only. Titrate slowly to manage GI side effects. Contraindicated with personal/family history of MTC or MEN 2.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 168,
    researchStatus: "FDA-approved (Ozempic/Wegovy)",
  },
  {
    name: "Tirzepatide",
    slug: "tirzepatide",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS", "GENERAL_WELLNESS"],
    description:
      "Dual GLP-1/GIP receptor agonist approved for type 2 diabetes and chronic weight management.",
    typicalDoseMin: 2.5,
    typicalDoseMax: 15,
    doseUnit: "mg",
    frequency: "once weekly",
    cycleWeeksMin: 12,
    cycleWeeksMax: 52,
    cautions: "Prescription-only. Titrate slowly; monitor for pancreatitis symptoms.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 120,
    researchStatus: "FDA-approved (Mounjaro/Zepbound)",
  },
  {
    name: "Retatrutide",
    slug: "retatrutide",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS"],
    description:
      "Triple agonist (GLP-1/GIP/glucagon receptor) currently in late-stage trials for weight management.",
    typicalDoseMin: 1,
    typicalDoseMax: 12,
    doseUnit: "mg",
    frequency: "once weekly",
    cycleWeeksMin: 12,
    cycleWeeksMax: 52,
    cautions: "Investigational — not yet FDA approved. Requires provider oversight via clinical trial or compounding pharmacy.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 144,
    researchStatus: "Investigational — in FDA clinical trials, not yet approved",
  },
  {
    name: "Liraglutide",
    slug: "liraglutide",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS"],
    description:
      "Daily GLP-1 receptor agonist approved for type 2 diabetes and weight management.",
    typicalDoseMin: 0.6,
    typicalDoseMax: 3,
    doseUnit: "mg",
    frequency: "once daily",
    cycleWeeksMin: 12,
    cycleWeeksMax: 52,
    cautions: "Prescription-only. Titrate slowly to manage GI side effects.",
    priceOneTimeCents: 0,
    isRx: true,
    halfLifeHours: 13,
    researchStatus: "FDA-approved (Victoza/Saxenda)",
  },
  {
    name: "Thymosin Alpha-1",
    slug: "thymosin-alpha-1",
    category: "HEALING_RECOVERY",
    goals: ["GENERAL_WELLNESS", "RECOVERY"],
    description:
      "Immune-modulating peptide studied in infection and immune-support research.",
    typicalDoseMin: 1,
    typicalDoseMax: 3,
    doseUnit: "mg",
    frequency: "twice weekly",
    cycleWeeksMin: 4,
    cycleWeeksMax: 12,
    cautions: "Limited long-term human data outside clinical trials.",
    priceOneTimeCents: 7999,
    isRx: false,
    halfLifeHours: 2,
    researchStatus: "Research-stage",
  },
  {
    name: "KPV",
    slug: "kpv",
    category: "HEALING_RECOVERY",
    goals: ["RECOVERY", "SKIN_HAIR", "GENERAL_WELLNESS"],
    description:
      "Tripeptide fragment of alpha-MSH studied for anti-inflammatory properties.",
    typicalDoseMin: 200,
    typicalDoseMax: 500,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 8,
    cautions: "Limited long-term human data.",
    priceOneTimeCents: 5499,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "Selank",
    slug: "selank",
    category: "COGNITIVE",
    goals: ["COGNITIVE", "GENERAL_WELLNESS"],
    description:
      "Synthetic peptide studied in anxiolytic and nootropic research contexts.",
    typicalDoseMin: 250,
    typicalDoseMax: 750,
    doseUnit: "mcg",
    frequency: "once or twice daily",
    cycleWeeksMin: 2,
    cycleWeeksMax: 8,
    cautions: "Often used intranasally; limited long-term human data.",
    priceOneTimeCents: 5799,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "Semax",
    slug: "semax",
    category: "COGNITIVE",
    goals: ["COGNITIVE", "GENERAL_WELLNESS"],
    description:
      "ACTH-derived peptide studied for cognitive and neuroprotective research applications.",
    typicalDoseMin: 250,
    typicalDoseMax: 750,
    doseUnit: "mcg",
    frequency: "once or twice daily",
    cycleWeeksMin: 2,
    cycleWeeksMax: 8,
    cautions: "Often used intranasally; limited long-term human data.",
    priceOneTimeCents: 5799,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "Epitalon",
    slug: "epitalon",
    category: "LONGEVITY",
    goals: ["LONGEVITY", "SLEEP", "GENERAL_WELLNESS"],
    description:
      "Tetrapeptide studied in longevity and telomerase-activity research.",
    typicalDoseMin: 5,
    typicalDoseMax: 10,
    doseUnit: "mg",
    frequency: "once daily",
    cycleWeeksMin: 2,
    cycleWeeksMax: 3,
    cautions: "Typically run in short cycles 2-4 times per year. Long-term human data is limited.",
    priceOneTimeCents: 6999,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "DSIP",
    slug: "dsip",
    category: "LONGEVITY",
    goals: ["SLEEP"],
    description:
      "Delta sleep-inducing peptide studied in sleep-architecture research.",
    typicalDoseMin: 100,
    typicalDoseMax: 300,
    doseUnit: "mcg",
    frequency: "once nightly",
    cycleWeeksMin: 2,
    cycleWeeksMax: 8,
    cautions: "Limited long-term human data.",
    priceOneTimeCents: 5499,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "Follistatin-344",
    slug: "follistatin-344",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN"],
    description:
      "Myostatin-inhibiting protein studied in muscle-growth research contexts.",
    typicalDoseMin: 100,
    typicalDoseMax: 300,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 2,
    cycleWeeksMax: 4,
    cautions: "Potent and expensive; limited human long-term data.",
    priceOneTimeCents: 14499,
    isRx: false,
    halfLifeHours: 1,
    researchStatus: "Research-stage",
  },
  {
    name: "IGF-1 LR3",
    slug: "igf-1-lr3",
    category: "GROWTH_HORMONE",
    goals: ["MUSCLE_GAIN", "RECOVERY"],
    description:
      "Long-acting IGF-1 analog studied in hypertrophy and recovery research.",
    typicalDoseMin: 20,
    typicalDoseMax: 100,
    doseUnit: "mcg",
    frequency: "once daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 6,
    cautions: "Can cause hypoglycemia; monitor blood sugar closely.",
    priceOneTimeCents: 9999,
    isRx: false,
    halfLifeHours: 24,
    researchStatus: "Research-stage",
  },
  {
    name: "HGH Fragment 176-191",
    slug: "hgh-fragment-176-191",
    category: "WEIGHT_LOSS",
    goals: ["FAT_LOSS"],
    description:
      "HGH fragment isolated for studied fat-metabolism effects independent of broader GH activity.",
    typicalDoseMin: 250,
    typicalDoseMax: 500,
    doseUnit: "mcg",
    frequency: "once or twice daily",
    cycleWeeksMin: 4,
    cycleWeeksMax: 12,
    cautions: "Limited long-term human data.",
    priceOneTimeCents: 6299,
    isRx: false,
    halfLifeHours: 2,
    researchStatus: "Research-stage",
  },
];

async function main() {
  console.log("Seeding peptide catalog and products...");

  for (const p of peptides) {
    const peptide = await prisma.peptide.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        category: p.category,
        goals: p.goals,
        description: p.description,
        typicalDoseMin: p.typicalDoseMin,
        typicalDoseMax: p.typicalDoseMax,
        doseUnit: p.doseUnit,
        frequency: p.frequency,
        cycleWeeksMin: p.cycleWeeksMin,
        cycleWeeksMax: p.cycleWeeksMax,
        cautions: p.cautions,
        isRx: p.isRx,
        halfLifeHours: p.halfLifeHours,
        researchStatus: p.researchStatus,
      },
      create: {
        name: p.name,
        slug: p.slug,
        category: p.category,
        goals: p.goals,
        description: p.description,
        typicalDoseMin: p.typicalDoseMin,
        typicalDoseMax: p.typicalDoseMax,
        doseUnit: p.doseUnit,
        frequency: p.frequency,
        cycleWeeksMin: p.cycleWeeksMin,
        cycleWeeksMax: p.cycleWeeksMax,
        cautions: p.cautions,
        isRx: p.isRx,
        halfLifeHours: p.halfLifeHours,
        researchStatus: p.researchStatus,
      },
    });

    if (p.isRx) continue; // rx peptides are gated behind a consult, not sold directly

    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: `${p.name} Vial`,
        description: p.description,
        priceOneTimeCents: p.priceOneTimeCents,
        peptideId: peptide.id,
      },
      create: {
        name: `${p.name} Vial`,
        slug: p.slug,
        description: p.description,
        priceOneTimeCents: p.priceOneTimeCents,
        peptideId: peptide.id,
        // Stripe price IDs are left null until configured in the Stripe
        // dashboard / env vars. The checkout route falls back gracefully.
        stripePriceIdOneTime: null,
        stripePriceIdSubscription: null,
      },
    });
  }

  console.log(`Seeded ${peptides.length} peptides and products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
